---

- name: Make sure pip3 package is installed.
  become: true
  ansible.builtin.package:
    name: python3-pip
    state: present
  tags: [mikrotik, preresquite]
  run_once: true

- name: Make sure librouteros Python library is installed.
  become: true
  ansible.builtin.pip:
    name: librouteros
    state: present
  tags: [mikrotik, preresquite]
  run_once: true

- name: Make sure sshpass package is installed.
  become: true
  ansible.builtin.package:
    name: sshpass
    state: present
  tags: [mikrotik, preresquite]
  run_once: true

- name: Make sure backup directory exists.
  become: true
  ansible.builtin.file:
    path: "{{ backup_dir }}"
    state: directory
    mode: "775"
    owner: "{{ backup_dir_owner }}"
  tags: [mikrotik, preresquite]
